name: Rp-plugins
version: '${project.version}'
main: quadrix.de.rpplugins.Warps
api-version: 1.19
author: 'Quadrix'
commands:
    warp:
    teleporter:
        description: Öffne den Warps-Teleporter
        usage: /teleporter
