name: Warps
version: '${project.version}'
main: theriseofavalon.de.warps.Warps
api-version: 1.19
commands:
    testgui:
    warp:
    teleporter:
        description: Öffne den Warps-Teleporter
        usage: /teleporter